name: GitHub CI/CD Pipelining Actions
run-name: ${{ github.actor }} GitHub CI/CD Pipelining Actions 🚀
on: [push]

jobs:
  CI-Insecure-Modules-Test:
    runs-on: ubuntu-latest
    env:
      working-directory-insecure: ./insecure
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: (cd insecure && npm install)
      - run: echo "npm is now checking for vulnerabilities"
      - run: (cd insecure && npm audit)

  CI-Messed-Up-JS-Detection:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: (cd mashup && npm install)
      - name: Check our linter for errors
        run: (cd mashup && npm install lint)

  CI-Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: (cd unittesting && npm install)
      - name: Check out our unit tests
        run: (cd unittesting && npm run test)
